---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ tuple . "maint" | include "benji.fullname" }}
  annotations:
    checksum/config: {{ .Values.benji.configuration | toYaml | sha256sum }}
  labels:
    app.kubernetes.io/name: {{ include "benji.name" . }}
    helm.sh/chart: {{ include "benji.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: benji
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "benji.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: maint
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "benji.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: maint
    spec:
      serviceAccountName: {{ tuple . "" | include "benji.fullname" }}
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: benji
          image: "{{ .Values.benji.image.registry }}/{{ .Values.benji.image.repository }}:{{ .Values.benji.image.tag }}"
          imagePullPolicy: {{ .Values.benji.image.pullPolicy }}
          securityContext:
            privileged: true
          command:
            - sleep
            - 3650h
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: TZ
              value: "{{ .Values.timeZone }}"
            - name: BENJI_INSTANCE
              value: {{ .Values.benji.instance | quote }}
            - name: PROM_PUSH_GATEWAY
              value: "{{- printf "%s-%s" .Release.Name .Values.pushgateway.nameOverride | trunc 63 | trimSuffix "-" -}}:9091"
            - name: BENJI_EXPERIMENTAL
              value: "1"
            - name: AMQP_USERNAME
              value: "{{ .Values.rabbitmq.rabbitmq.username }}"
            - name: AMQP_PASSWORD
              value: "{{ .Values.rabbitmq.rabbitmq.password }}"
            - name: AMQP_HOST
              value: "{{ printf "%s-%s" .Release.Name .Values.rabbitmq.nameOverride | trunc 63 | trimSuffix "-" }}"
            - name: AMQP_PORT
              value: "{{ .Values.rabbitmq.service.port }}"
            - name: AMQP_VIRTUAL_HOST
              value: "/"
          volumeMounts:
            - name: benji-config
              mountPath: /benji/etc
{{- if .Values.benji.volumeMounts -}}
            {{- toYaml .Values.benji.volumeMounts | nindent 12 }}
{{- end -}}
{{- with .Values.benji.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
{{- end }}
      hostNetwork: false
      volumes:
        - name: benji-config
          configMap:
            name: {{ tuple . "" | include "benji.fullname" }}
{{- if .Values.benji.volumes -}}
        {{ toYaml .Values.benji.volumes | nindent 8 }}
{{- end -}}
{{- with .Values.benji.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.benji.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.benji.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
{{- end }}
