timeZone: Europe/Berlin

benji:
  image:
    registry: docker.io
    repository: elementalnet/benji
    tag: latest
    pullPolicy: Always

  instance: benji

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

  configuration:
    configurationVersion: '1'
    databaseEngine: sqlite:////tmp/benji.sqlite
    defaultStorage: storage-1
    storages:
      - name: storage-1
        storageId: 1
        module: file
        configuration:
          path: /tmp/benji-data
    ios:
      - name: file
        module: file

  # Volumes and volume mounts can be used to mount Ceph configuration and credentials, backup sources or storages into
  # the Benji container.
  volumes: []
  volumeMounts: []

  api:
    port: 7746
    replicas: 1
    threadsPerReplica: 10

operator:
  image:
    registry: docker.io
    repository: elementalnet/benji-k8s-operator
    tag: latest
    pullPolicy: Always

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

fsfreeze:
  enabled: false

  image:
    registry: docker.io
    repository: centos
    tag: 7
    pullPolicy: IfNotPresent

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

postgresql:
  enabled: true
  postgresqlUsername: benji
  postgresqlDatabase: benji
  postgresqlPassword: benji-pass
  persistence: false

pushgateway:
  image:
    registry: docker.io
    repository: prom/pushgateway
    tag: v0.8.0
    pullPolicy: IfNotPresent
  nameOverride: pushgateway

rabbitmq:
  nameOverride: rabbitmq
  persistence:
    enabled: false
  rabbitmq:
    username: benji
    password: benji-pass
  networkPolicy:
    enabled: true
    allowExternal: False
