---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: benjioperatorconfigs.benji-backup.me
  labels:
    component: benji
  annotations:
    helm.sh/hook: crd-install
spec:
  scope: Namespaced
  group: benji-backup.me
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - reconciliationSchedule
                - jobTemplate
              properties:
                reconciliationSchedule:
                  type: string
                cleanupSchedule:
                  type: string
                jobTemplate:
                  type: object
                  x-kubernetes-embedded-resource: true
                  x-kubernetes-preserve-unknown-fields: true
                  properties:
                    apiVersion:
                      type: string
                      pattern: "^batch/v1$"
                    kind:
                      type: string
                      pattern: "^Job$"
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
  names:
    kind: BenjiOperatorConfig
    plural: benjioperatorconfigs
    singular: benjioperatorconfig
    shortNames:
      - benjiocs
      - benjioc

